# fly.toml file generated for lively-sky-3924 on 2023-02-16T11:32:26+02:00

app = "lively-sky-3924"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
